name: Demo Workflow

on: workflow_dispatch

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Hello world"
  job-bis:
    needs: ["demo-job"]
    runs-on: ubuntu-slim
    steps:
      - name: Get Google infos
        run: curl https://google.com
