name: React Base
on: ["workflow_dispatch","push"]

jobs:
    test-git:
        runs-on: ubuntu-latest
        steps:
            - name: Check files
              run: ls   
    build-app:
        runs-on: ubuntu-latest
        steps:
            - name: Get Source files
              uses: actions/checkout@v6
            - name: Install dependancies
              run: npm ci 
            - name: Build app
              run: npm run build
            - name: Test build completion
              run: ls dist/index.html     